# Site settings
title: Coffee & Coding
header-img: img/home-bg.png
email: takiaroc5@gmail.com
copyright_name: takiarochelle
description: > # this means to ignore newlines until "baseurl:"
  Learning to code one syntax error at a time. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  takiarochelle
learn_profile: takiarochelle
email_username: takiaroc5@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
